services:
  bank-core:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-core:latest
    container_name: bank-core
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-8082}:${PORT:-8082}"
    networks:
      - tirenn-net

networks:
  tirenn-net:
    external: true
