services:
  bank-core:
    build:
      context: ./backend/core
      dockerfile: Dockerfile
    image: bank-core:latest
    container_name: bank-core
    restart: always
    env_file:
      - ./backend/core/.env
    networks:
      - tirenn-net

  bank-ai:
    build:
      context: ./backend/ai-service
      dockerfile: Dockerfile
    image: bank-ai:latest
    container_name: bank-ai
    restart: always
    env_file:
      - ./backend/ai-service/.env
    depends_on:
      - bank-core
    networks:
      - tirenn-net

  bank-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: bank-frontend:latest
    container_name: bank-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "127.0.0.1:${FE_PORT:-7081}:${FE_PORT:-7081}"
    depends_on:
      - bank-core
      - bank-ai
    networks:
      - tirenn-net

networks:
  tirenn-net:
    external: true
