services:
  bank-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-ai:latest
    container_name: bank-ai
    restart: always
    env_file:
      - .env
    networks:
      - tirenn-net

networks:
  tirenn-net:
    external: true
