services:
  bank-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-ai
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT:-8083}:${PORT:-8083}"
    networks:
      - tirenn-net

networks:
  tirenn-net:
    external: true
